Remove space that results in error
Related to Issue #10 

This space causes the compiler to not load the project. 

```
Error: Unexpected space at position "25" of condition "$(LessDisableUrlRewriting )" == ''
```